### ISSUE TITLE
404 not found sl for linux

### ISSUE THREAD

**Issue by syntroniks** [StratifyLabs/StratifyOS#232]
https://stratifylabs.page.link/sl_linux_x86_64 does not point to a `sl` binary I can download for linux builds

following instructions from https://github.com/StratifyLabs/StratifyOS/blob/da36672078b9497b5dc297c84967cbcd3d02e52f/guides/Getting-Started.md

**Comment by tyler-gilbert** [comment]
OK. There are a couple typos there. This is how the links are setup. I will update that guide.

<img width="457" alt="sl-links" src="https://user-images.githubusercontent.com/6136781/91186782-a974f800-e6ac-11ea-84a7-66793fa7bb2c.png">

**Comment by syntroniks** [comment]
Resolved in #236
